dataset_config:
  okvqa:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    zoo_requirements:
    - coco.defaults
    - okvqa.defaults
    images:
      train:
      - okvqa/defaults/images/
      val:
      - okvqa/defaults/images/
      test:
      - okvqa/defaults/images/
    features:
      train:
      - coco/defaults/features/trainval2014.lmdb
      val:
      - coco/defaults/features/trainval2014.lmdb
      test:
      - coco/defaults/features/trainval2014.lmdb
    annotations:
      train:
      - okvqa/defaults/annotations/imdb_train2014.npy
      val:
      - okvqa/defaults/annotations/imdb_val2014.npy
      test:
      - okvqa/defaults/annotations/imdb_val2014.npy
    max_features: 100
    processors:
      text_processor:
        type: vocab
        params:
          max_length: 14
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: okvqa/defaults/extras/vocabs/vocabulary_100k.txt
          preprocessor:
            type: simple_sentence
            params: {}
      answer_processor:
        type: vqa_answer
        params:
          num_answers: 10
          vocab_file: okvqa/defaults/extras/vocabs/answers_okvqa.txt
          preprocessor:
            type: simple_word
            params: {}
      context_processor:
          type: fasttext
          params:
            download_initially: false
            max_length: 50
            model_file: wiki.en.bin
      bbox_processor:
          type: bbox
          params:
            max_length: 50
    return_features_info: false #TODO: check what it is