model_config:
  visual_bert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: classification
    num_labels: 4662
    pooler_strategy: vqa
    use_knwlg: true
    knwlg_size: 300
    # losses:
    # - type: multi
    #   params:
    #   - type: logit_bce
    #     weight: 1
    #     params: {}
    #   - type: knwlg_reg
    #     weight: 100
    #     params: {}
    losses:
    - type: logit_bce
    - type: knwlg_reg
      params: {"weight": 100}

dataset_config:
  okvqa:
    use_ontology: true
    max_entity_len: 10
    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

evaluation:
  metrics:
  - vqa_accuracy

training:
  batch_size: 64
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 22000
  find_unused_parameters: true
  early_stop:
    criteria: okvqa/vqa_accuracy
    minimize: false

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
